# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchText', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchBox',
        ),
    ]
