# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_auto_20170328_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.IntegerField()),
                ('search_term', models.CharField(max_length=255)),
                ('data_response', models.TextField()),
                ('page_num', models.IntegerField()),
                ('date_cached', models.DateField()),
            ],
            options={
                'db_table': 'searchCache_tbl',
            },
        ),
    ]
